[project]
name = "peptidemtr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "pip>=25.3",
    "numpy>=2.2.6",
    "scipy>=1.15.3",
    "pandas>=2.3.3",
    "datasets>=3.5.0",
    "lightning<=2.6.1",
    "seaborn>=0.13.2",
    "plotnine>=0.15.2",
    "matplotlib>=3.10.8",
    "rdkit>=2025.9.3",
    "torch>=2.9.1",
    "scikit-learn>=1.7.2",
    "transformers>=4.57.3",
    "peft>=0.19.1",
    "ripgrep>=15.0.0",
]

[project.optional-dependencies]
baselines = [
    "xgboost>=2.1.4",
    "statsmodels>=0.14.4",
]
chemeleon = [
    "chemprop>=2.2.0",
    "fastprop>=1.1.1",
    "polaris-lib>=0.11.10",
    "scikit-mol>=0.6.0",
    "scikit-posthocs>=0.11.4",
    "statsmodels>=0.14.4",
    "zarr<3",
]
